backend:
  name: github
  repo: maxmurdoch/flock

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "src/pages/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Template key", name: "templateKey", widget: "string"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - name: "button"
                label: "Button"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "To", name: "to", widget: "string"}
          - label: 'First testimonials'
            name: 'firstTestimonial'
            widget: 'list'
            fields:
              - {label: 'Author', name: 'author', widget: 'string'}
              - {label: 'Quote', name: 'quote', widget: 'markdown'}
              - {label: 'Image', name: 'image', widget: 'image'}
          - label: 'Second testimonials'
            name: 'secondTestimonial'
            widget: 'list'
            fields:
              - {label: 'Author', name: 'author', widget: 'string'}
              - {label: 'Quote', name: 'quote', widget: 'markdown'}
              - {label: 'Image', name: 'image', widget: 'image'}
          - label: 'How Flock works'
            name: 'howFlockWorks'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - name: 'listOfHow'
                label: 'List of how'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Text', name: 'text', widget: 'string'}
          - label: 'Stop worrying'
            name: 'stopWorrying'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'Reasons'
                name: 'reasons'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'} 
                  - {label: 'Text', name: 'text', widget: 'markdown'} 
          - label: 'What kind of pilot?'
            name: 'kindOfPilot'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'string'}
              - label: 'Pilots'
                name: 'pilots'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'} 
                  - {label: 'Text', name: 'text', widget: 'markdown'} 
                  - {label: 'Icon', name: 'icon', widget: 'image'} 
          - label: 'Risk'
            name: 'risk'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'Calculations'
                name: 'calculations'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'} 
                  - {label: 'Text', name: 'text', widget: 'markdown'} 
                  - {label: 'Icon', name: 'icon', widget: 'image'} 
          - label: 'How Flock works'
            name: 'howFlockWorks'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'List of how'
                name: 'listOfHow'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'} 
                  - {label: 'Text', name: 'text', widget: 'markdown'} 
          - label: 'What Flock covers'
            name: 'whatFlockCovers'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'List of what flock covers'
                name: 'listOfWhatFlockCovers'
                widget: 'list'
                fields:
                  - {label: 'Text', name: 'text', widget: 'string'} 
          - label: 'Featured'
            name: 'featured'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Image', name: 'image', widget: 'image'}

      - name: about
        label: About
        file: "src/pages/about/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}

  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: segment
    label: Segment
    folder: segment
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: heroMainText, label: Hero main text }

